### ISSUE TITLE
USER STORY: Create an account

### ISSUE THREAD

**Issue by Krnsand** [Krnsand/pp4-restaurants#2]
As a **site user**, I can **create an account** so that **I can manage my bookings**.

## Acceptance Criteria
  * Sign-up form with personal information
  * Manage my bookings

## Tasks
   - [x] Design HTML form
   - [x] Style with CSS
   - [x] Secure form with CSRF
